# This file was generated by Nuitka and describes the types of the
# created shared library.

# At this time it lists only the imports made and can be used by the
# tools that bundle libraries, including Nuitka itself. For instance
# standalone mode usage of the created library will need it.

# In the future, this will also contain type information for values
# in the module, so IDEs will use this. Therefore please include it
# when you make software releases of the extension module that it
# describes.

import ui.plazaPage
import sqlite3
import CFAPI
import curseforge
import fetchImageTask
import future
import task
import taskManager
import dataclasses
import PyQt5.QtCore
import PyQt5.QtGui
import Client.Clients
import concurrent.future
import concurrent.task
import weakref
import psutil
import SchemaClasses
import Utils
import enum
import urllib.parse
import datetime
import jsonpickle
import backends
import cache_keys
import models
import patcher
import policy
import serializers
import session
import contextlib
import inspect
import logging
import urllib3
import _utils
import base
import dynamodb
import gridfs
import mongodb
import redis
import sqlite
import filesystem
import abc
import collections
import pickle
import warnings
import requests
import boto3
import boto3.dynamodb.types
import boto3.resources.base
import botocore.exceptions
import requests_cache.backends.base
import pathlib
import shutil
import threading
import gridfs.errors
import pymongo
import pymongo.errors
import policy.expiration
import os.path
import tempfile
import time
import platformdirs
import models.response
import json
import hashlib
import requests.models
import url_normalize
import raw_response
import request
import response
import attr
import urllib3.response
import requests.cookies
import requests.structures
import expiration
import settings
import directives
import actions
import email.utils
import fnmatch
import math
import cattrs
import pipeline
import preconf
import decimal
import cattr
import requests.exceptions
import ujson
import itsdangerous
import bson
import yaml
import requests.hooks
import PyQt5.QtWidgets
import qfluentwidgets
import singleModWidget
import concurrent
import concurrent.curseforgeTask
import curseforge.Utils
import utils.FetchImageManager
import _pickle

# This is not Python source even if it looks so. Make it clear for
# now. This was decided by PEP 484 designers.
__name__ = ...

