# -*- coding: utf-8 -*-
# Form implementation generated from reading ui file '.\modDetailPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from qfluentwidgets import BodyLabel, CardWidget, HyperlinkLabel, PixmapLabel, SmoothScrollArea, TitleLabel, PushButton

from .modDetailPageBody import ModDetailPageBody
from .modDetailPage_DL import ModDetailPage_DL
from ..concurrent import Future
from ..curseforge import SchemaClasses as schemas
from ..managers import fetchImageManager
from ..model.modDLLinkModel import ModDLLinkModel


class ModDetailPage(QtWidgets.QFrame):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.ui = Ui_Frame()
        self.ui.setupUi(self)
        self.ui.retranslateUi(self)

    # TODO
    def onCategoryIconClicked(self, icon: PixmapLabel):
        raise NotImplementedError

    def appendCategoryIcon(self, fut: Future):
        w = fut.getExtra("iconWidget")
        w: PixmapLabel
        self.ui.categoryIcons.addWidget(
            w,
            alignment=QtCore.Qt.AlignRight
        )

    def setModInfo(self, mod: schemas.Mod):
        # set mod name
        self.ui.TitleLabel.setText(mod.name)

        # set mod author
        if len(mod.authors) == 1:
            self.ui.authorHyperLinkLabel.setText(mod.authors[0].name)
            self.ui.authorHyperLinkLabel.setUrl(mod.authors[0].url)
        else:
            self.ui.authorHyperLinkLabel.setText(mod.authors[0].name)
            self.ui.authorHyperLinkLabel.setUrl(mod.authors[0].url)
            for author in mod.authors[1:]:
                linkLabel = HyperlinkLabel(self.ui.authorWidget)
                linkLabel.setText(author.name)
                linkLabel.setUrl(author.url)
                self.ui.authorWidget.layout().addWidget(linkLabel)
        # set mod source
        self.ui.sourceHyperLinkLabel.setText("CurseForge")
        self.ui.sourceHyperLinkLabel.setUrl(mod.links.websiteUrl)
        # set mod icon
        fetchImageManager.asyncFetch(mod.logo.thumbnailUrl, self.ui.modIcon, verify=False)
        # set mod categories
        for category in mod.categories:
            icon = PixmapLabel(self.ui.titleCard)
            icon.setMinimumSize(36, 36)
            icon.setMaximumSize(36, 36)
            icon.setObjectName(f"categoryIcon-{category.id}-{category.name}-{category.url}")
            fut = fetchImageManager.asyncFetch(
                category.iconUrl,
                icon,
                verify=False,
                size=(36, 36),
                successCallback=self.appendCategoryIcon
            )
            fut.setExtra("iconWidget", icon)

    @staticmethod
    def getInstance(mod: schemas.Mod):
        modDetailPage = ModDetailPage()
        modDetailPage.setModInfo(mod)
        modDetailPage.ui.modFilesInterface.ui.TableView.setModel(model := ModDLLinkModel.getModel(mod))
        model.modelReset.connect(modDetailPage.ui.modFilesInterface.onModFilesGot)
        return modDetailPage


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(800, 600)
        self.gridLayout = QtWidgets.QGridLayout(Frame)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(5, 10, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 5, 1, 1)
        self.mainWidget = QtWidgets.QVBoxLayout()
        self.mainWidget.setObjectName("mainWidget")
        self.titleCard = CardWidget(Frame)
        self.titleCard.setObjectName("titleCard")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.titleCard)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.modTitle = QtWidgets.QHBoxLayout()
        self.modTitle.setObjectName("modTitle")
        self.modIcon = PixmapLabel(self.titleCard)
        self.modIcon.setMinimumSize(QtCore.QSize(96, 96))
        self.modIcon.setMaximumSize(QtCore.QSize(96, 96))
        self.modIcon.setObjectName("modIcon")
        self.modTitle.addWidget(self.modIcon)
        spacerItem1 = QtWidgets.QSpacerItem(8, 8, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.modTitle.addItem(spacerItem1)
        self.modInfoLayout = QtWidgets.QVBoxLayout()
        self.modInfoLayout.setObjectName("modInfoLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.TitleLabel = TitleLabel(self.titleCard)
        self.TitleLabel.setObjectName("TitleLabel")
        self.horizontalLayout.addWidget(self.TitleLabel)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.categoryIcons = QtWidgets.QHBoxLayout()
        self.categoryIcons.setObjectName("categoryIcons")
        self.horizontalLayout.addLayout(self.categoryIcons)
        self.modInfoLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.authorWidget = QtWidgets.QWidget(self.titleCard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.authorWidget.sizePolicy().hasHeightForWidth())
        self.authorWidget.setSizePolicy(sizePolicy)
        self.authorWidget.setObjectName("authorWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.authorWidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.authorTag = BodyLabel(self.authorWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.authorTag.sizePolicy().hasHeightForWidth())
        self.authorTag.setSizePolicy(sizePolicy)
        self.authorTag.setMinimumSize(QtCore.QSize(0, 20))
        self.authorTag.setMaximumSize(QtCore.QSize(16777215, 20))
        self.authorTag.setStyleSheet("BodyLabel {\n"
                                     "    background-color: rgba(199, 199, 199, 50%);\n"
                                     "    border-radius: 4px;\n"
                                     "    padding-left: 3px solid rgba(223, 239, 232, 80%);\n"
                                     "    padding-right: 3px solid rgba(223, 239, 232, 80%);\n"
                                     "}")
        self.authorTag.setAlignment(QtCore.Qt.AlignCenter)
        self.authorTag.setObjectName("authorTag")
        self.horizontalLayout_4.addWidget(self.authorTag)
        self.authorHyperLinkLabel = HyperlinkLabel(self.authorWidget)
        self.authorHyperLinkLabel.setObjectName("authorHyperLinkLabel")
        self.horizontalLayout_4.addWidget(self.authorHyperLinkLabel)
        self.horizontalLayout_2.addWidget(self.authorWidget)
        self.sourceWidget = QtWidgets.QWidget(self.titleCard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sourceWidget.sizePolicy().hasHeightForWidth())
        self.sourceWidget.setSizePolicy(sizePolicy)
        self.sourceWidget.setObjectName("sourceWidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.sourceWidget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.sourceTag = BodyLabel(self.sourceWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sourceTag.sizePolicy().hasHeightForWidth())
        self.sourceTag.setSizePolicy(sizePolicy)
        self.sourceTag.setMinimumSize(QtCore.QSize(0, 20))
        self.sourceTag.setMaximumSize(QtCore.QSize(16777215, 20))
        self.sourceTag.setStyleSheet("BodyLabel {\n"
                                     "    background-color: rgba(199, 199, 199, 50%);\n"
                                     "    border-radius: 4px;\n"
                                     "    padding-left: 3px solid rgba(223, 239, 232, 80%);\n"
                                     "    padding-right: 3px solid rgba(223, 239, 232, 80%);\n"
                                     "}")
        self.sourceTag.setAlignment(QtCore.Qt.AlignCenter)
        self.sourceTag.setObjectName("sourceTag")
        self.horizontalLayout_5.addWidget(self.sourceTag)
        self.sourceHyperLinkLabel = HyperlinkLabel(self.sourceWidget)
        self.sourceHyperLinkLabel.setObjectName("sourceHyperLinkLabel")
        self.horizontalLayout_5.addWidget(self.sourceHyperLinkLabel)
        self.horizontalLayout_2.addWidget(self.sourceWidget)
        self.modInfoLayout.addLayout(self.horizontalLayout_2)
        self.modTitle.addLayout(self.modInfoLayout)
        self.horizontalLayout_3.addLayout(self.modTitle)
        self.mainWidget.addWidget(self.titleCard)
        spacerItem3 = QtWidgets.QSpacerItem(5, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.mainWidget.addItem(spacerItem3)
        self.bodyCard = CardWidget(Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bodyCard.sizePolicy().hasHeightForWidth())
        self.bodyCard.setSizePolicy(sizePolicy)
        self.bodyCard.setObjectName("bodyCard")
        self.mainWidget.addWidget(self.bodyCard)
        self.gridLayout.addLayout(self.mainWidget, 1, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(10, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem4, 0, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 1, 2, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(5, 10, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 1, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(10, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem7, 2, 1, 1, 1)
        self.SmoothScrollArea = SmoothScrollArea(Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SmoothScrollArea.sizePolicy().hasHeightForWidth())
        self.SmoothScrollArea.setSizePolicy(sizePolicy)
        self.SmoothScrollArea.setMinimumSize(QtCore.QSize(160, 0))
        self.SmoothScrollArea.setWidgetResizable(True)
        self.SmoothScrollArea.setObjectName("SmoothScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 158, 558))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.SmoothScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.SmoothScrollArea, 1, 4, 1, 1)

        self.backButton = PushButton(Frame)
        self.gridLayout.addWidget(self.backButton, 2, 4, 1, 1)

        self.SmoothScrollArea.viewport().setStyleSheet(
            "background-color: transparent;"
        )
        self.bodyWidget = ModDetailPageBody(self.bodyCard)
        self.bodyCard.setLayout(QtWidgets.QVBoxLayout(self.bodyCard))
        self.bodyCard.layout().setContentsMargins(0, 0, 0, 0)
        self.bodyCard.layout().addWidget(self.bodyWidget)
        self.modFilesInterface = ModDetailPage_DL(self.bodyCard)
        self.descriptionInterface = QtWidgets.QWidget(self.bodyCard)
        self.bodyWidget.addSubInterface(
            self.descriptionInterface,
            "descriptionInterface",
            "描述"
        )
        self.bodyWidget.addSubInterface(
            self.modFilesInterface,
            "modFilesInterface",
            "下载"
        )

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.TitleLabel.setText(_translate("Frame", "<Mod Name>"))
        self.authorTag.setText(_translate("Frame", "作者"))
        self.authorHyperLinkLabel.setText(_translate("Frame", "[作者]"))
        self.sourceTag.setText(_translate("Frame", "来源"))
        self.sourceHyperLinkLabel.setText(_translate("Frame", "[来源]"))

        self.backButton.setText(_translate("Frame", "返回"))
